baseURL = "https://themanticoreproject.com/"
languageCode = "en-us"
title = "The Manticore Project"
theme = "manticore"

[params]
  description = "Crowdsourced open source offensive and defensive security tools to heighten the security posture of the community as a whole."
  longDescription = "A collective of Go developers and security researchers dedicated to building security tools with the shared goal of strengthening the overall security posture of the community."
  githubOrg = "https://github.com/TheManticoreProject"
  discord = "https://discord.gg/TVmVFCp7ky"
  linkedin = "https://www.linkedin.com/company/themanticoreproject/"
  youtube = "https://www.youtube.com/@The-Manticore-Project"
  reddit = "https://www.reddit.com/r/TheManticoreProject/"
  website = "https://themanticoreproject.com/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    style = "monokai"
    lineNos = false

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 1
  [[menu.main]]
    name = "Libraries"
    url = "/libraries/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 4
